import "./AppBlock.css";

import { useState } from "react";

export default function AppBlock({ slug }) {
    const url = `https://asha-demo.vercel.app/api/get-app/${slug}`;
    const [copied, setCopied] = useState(false);

    const copy = () => {
        navigator.clipboard.writeText(url);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="app-block">
            <div className="app-block-toolbar">
                <span className="app-block-label">✦ App generated by Asha</span>
                <div className="app-block-actions">
                    <button className="app-block-btn" onClick={copy}>
                        {copied ? "Copied!" : "Copy Link"}
                    </button>
                    <a className="app-block-btn" href={url} target="_blank" rel="noreferrer">
                        Open ↗
                    </a>
                </div>
            </div>
            <iframe
                src={url}
                className="app-block-frame"
                sandbox="allow-scripts allow-same-origin allow-forms"
                title="Generated App"
            />
        </div>
    );
}